### ISSUE TITLE
"WARNING: root: Chain A has none/missing backbone atoms to calculate the hinge" for AlphaFold generated structures

### ISSUE THREAD

**Issue by Jess-Sun** [Pranavkhade/PACKMAN#64]
Dear maintainer, I am reaching out because I encountered an issue with file compatibility.

I am unable to get PACKMAN to work with PDB files generated by AlphaFold e.g. [https://alphafold.ebi.ac.uk/entry/O95140]
It does work with the crystal structure from the PDB database: 6JFK, but the structure is incomplete so AlphaFold compatibility would be preferable. 
It gives the error: "WARNING: root: Chain A has none/missing backbone atoms to calculate the hinge". I have tried with the CLI, GUI and web server implementations as well as with the AlphaFold generated CIF file and they all give the same error. 

If you have any guidance on what adjustments may need to be made when using AlphaFold generated structures that would be much appreciated. 

Best regards

**Comment by Jess-Sun** [comment]
Hi Pranav,

Thanks so much for your time, glad it will likely be a quick fix.
I have tried other AlphaFold structures, and it resulted in the same error.
These include: Q9Y6Y1, P12755, P42898, P51801 and Q9P2R6

Best,
Jess

**Comment by Pranavkhade** [comment]
Hi. 

Thank you for the information. I just tested the PDB and CIF structures on my machine and they are working (recorded video linked at the bottom). 

Please let me know if you are doing any step differently.

* Did you make any changes to the files after download? 
* Are you using the latest version of py-packman?
* What python version are you using?

I appreciate your patience.

Thanks,
Pranav

https://github.com/user-attachments/assets/7865abaa-b5f8-438a-bcc0-fec33b0a53cc

**Comment by Jess-Sun** [comment]
Hi Pranav, 

Thanks for your response, to answer your questions:

- Only the file name was changed after download
- PACKMAN ver 1.4.13 was used
- python ver 3.10.12 was used

After watching your video, the main difference seems to be the alpha value that was set. I had used 2.8 while you used 4. I have tried again with the web server and the GUI and PACKMAN does indeed run with AlphaFold generated files when alpha is set to 4. I am a bit surprised as the paper only indicated that the number and length of hinges may change due to changing alpha. Alpha of 2.8 ran without problems for the structure obtained from the PDB database. 

Would 4 be your recommended default value for alpha? I am planning to run PACKMAN on about 600 proteins, can AlphaFold structures be assumed to be mostly in open form for alpha value purposes?

**Comment by Pranavkhade** [comment]
It's great to know that it worked. However, the error you originally posted doesn't relate to alpha values, so I will investigate further. Thank you for reporting

Answer to your question: 
Different structures will have different protein packing, so there is no single answer to the alpha value; No. 4 is just a reasonably high number I put so that I will get some hinges, as a higher alpha value means more connections, as mentioned in the paper. 

The recommended strategy is to start from 2.8, gradually increasing the value since you find critical hinges at lower alpha values. Since you are planning to use it for 600 structures, it is best done with API. If you do not have a programming experience use this script or use it as a reference to scan alpha values starting from 2.8 to whatever is your desired range : https://github.com/Pranavkhade/PACKMAN/blob/master/additional%20codes/ScanAlpha.py

Please let me know whenever you think that this is issue is resolved.

**Comment by Pranavkhade** [comment]
I consider the issue resolved since a long time has passed since the last suggested resolution without a comment. Thanks

Pranav
